name: build

on:
  push: # Run this workflow on every push to any branch
  workflow_dispatch: # Allow workflow to be run manually
  schedule:
    - cron: '0 0 * * 0' # “At 00:00 (UTC) every Sunday.”

jobs:
  # Build project and install dependencies
  flutter_setup:
    name: Flutter Build
    runs-on: macos-10.15
    steps:
      - id: checkout
        name: Checking Out Repository
        uses: actions/checkout@v2
      - id: java
        name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - id: flutter
        name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
      - id: dependencies
        name: Installing Dependencies
        run: flutter pub get
    
  # Lint the codebase for bugs
  dart_lint:
    name: Dart Lint
    needs: flutter_setup
    runs-on: macos-10.15
    steps:
      - id: lint
        name: Dart Linter
        run: flutter analyze

  # Run the unit tests
#   unit_test:
#     name: Unit Test
#     needs: dart_lint
  
  # Run the widget tests
#   widget_test:
#     name: Widget Test
#     needs: unit_test

  # Run the integration tests
#   integration_test:
#     name: Integration Test
#     needs: widget_test
  
  # Deploy the build to the app stores
#   deploy:
#     name: Deploy App
#     needs: integration_test
#     strategy:
#       matrix:
#         platform: [iOS, Android]

#   labeler:
#     if: always() 
#     runs-on: ubuntu-latest
#     steps
#       - id: 

# FROM THE OLD BUILD CI WORKFLOW:
# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#     - name: checkout repository
#       uses: actions/checkout@v2
#     - name: setup java
#       uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - name: setup Flutter environment
#       uses: subosito/flutter-action@v1
#       with:
#         flutter-version: '1.22.4'
#     - name: install dependencies
#       run: flutter pub get
#     - name: build apk
#       run: flutter build apk
#     - name: build ios
#       run: flutter build ios --release --no-codesign
