name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! Thanks for submitting an issue to PrepTimer, with your help we can make this tool great for years to come.'
        pr-message: 'You rock! Thanks for submitting this pull request to PrepTimer, with your help we can make this tool great for years to come.'
